// examples/react-textarea/src/Editor.js
import React, { useState } from "react";

import { GrammarlyTextArea } from "@grammarly/react-textarea";
import { demoClientId, demoText } from "./demo";
import "./style.css";

export const Editor = () => {
  const [value, setValue] = useState(demoText);
  return (
    <GrammarlyTextArea
      clientId={demoClientId}
      value={value}
      onChange={(event) => {
        setValue(event.target.value);
      }}
      rows={20}
    />
  );
};

// examples/vue-textarea/src/components/Editor.vue
<script>
import { GrammarlyTextArea } from "@grammarly/vue-textarea";
import { demoText, demoClientId } from "./demo";

export default {
  data: () => ({ text: demoText, clientId: demoClientId }),
  components: { GrammarlyTextArea },
};
</script>

<template>
  <GrammarlyTextArea v-model="text" rows="20" :clientId="clientId" />
</template>
